import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Shop",
  description: "Generated by tanviirshanto",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning>
          <div><Toaster/></div>
          <div className="flex flex-wrap gap-3 justify-center mt-5 " > <Link href="/products"> Products </Link> <Link href="/invoice"> Invoice </Link> <Link href="/sells"> Sells </Link> <Link href="/purchases"> Purchases </Link> <Link href="/stocks"> Stocks </Link>
          <Link href="/customers"> Customers </Link> <Link href="/configs"> Configs </Link>  </div>
        {children}
      </body>
    </html>
  );
}
